name: 🐞 Bug report
description: "Report a bug or something that is otherwise not working as expected."
labels: ["bug"]
body:
- type: textarea
  id: description
  attributes:
    label: Description of Issue
    description: "Please provide a clear and concise description of the bug below."
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: Plugin Version
    description: "Please state the version number of this plugin that exhibits the bug. If this is not the most recent release then please try updating to the latest version before reporting the issue."
  validations:
    required: true
- type: input
  id: appliance
  attributes:
    label: AEG/Electrolux Appliance(s)
    description: "If this issue relates to a specific appliance then please provide the manufacturer, model, and product number (PNC). These details can be found on the ratings label underneath the robot."
    placeholder: "e.g. AEG RX9-2-4ANM 900 277 479"
  validations:
    required: false
- type: input
  id: homekitapp
  attributes:
    label: HomeKit App(s)
    description: "If this issue relates to a specific HomeKit app then please provide details."
    placeholder: "e.g. Apple Home, Elgato Eve, Home+ 4, Hesperus, etc."
  validations:
    required: false
- type: checkboxes
  id: diagnostics
  attributes:
    label: Diagnostic Checks
    description: "Indicate the steps that have you have taken to rule-out problems with the AEG/Electrolux servers or appliance."
    options:
      - label: "AEG iPhone app is able to control the appliance."
  validations:
    required: false
- type: textarea
  id: log
  attributes:
    label: Log File
    description: "Please copy/paste relevant log entries. Attach longer logs as a text file. Do NOT use a screenshot. These logs should be captured with Homebridge in debug mode (enabled using its -D command line option)."
    render: shell
  validations:
    required: false
