blank_issues_enabled: false
contact_links:
  - name: 📧 Contact HOOBS support
    url: https://support.hoobs.org/ticket
    about: This is not a HOOBS plugin. Contact the HOOBS support team with any issues that cannot be reproduced with a vanilla (non-HOOBS) Homebridge installation.
