name: Create GitHub Release

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: CSchoel/release-notes-from-changelog@v1
        with:
          begin-pattern: '/^## \\[v${RELEASE_VERSION}\\]/'
          link-pattern: '^\\[v${RELEASE_VERSION}\\]:'
          version: "${{ github.event.inputs.version }}"

      - name: Create Release using GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create
          -d
          -F RELEASE.md
          -t "Version $RELEASE_VERSION"
          ${GITHUB_REF#refs/*/}
