# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Close Stale Issues and PRs

on:
  schedule:
  - cron: '30 1 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v7
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open for 30 days without activity. This issue will be closed in 5 days unless the stale label is removed or a comment added.'
        close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
        stale-issue-label: 'stale'
        days-before-issue-stale: 30
        days-before-issue-close: 7
        close-pr-message: 'This project does not accept PRs.'
        stale-pr-label: 'wontfix'
        days-before-pr-stale: 0
        days-before-pr-close: 0
