name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.9.0, 20.x, 22.x]
        homebridge-version: ['^1.8.0', '^2.0.0-beta.0']

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Use homebridge ${{ matrix.homebridge-version }}
        run: npm install homebridge@${{ matrix.homebridge-version }}

      - name: Copy homebridge configuration
        run: cp -R ./.devcontainer/.homebridge ~/

      - name: Build the project
        run: npm run build

      - name: Retrieve an Electrolux Group API Access Token
        run: echo "ELECTROLUX_ACCESS_TOKEN=$(curl -s https://www.thouky.co.uk/api/oauth/electrolux/${{ secrets.ELECTROLUX_API_KEY }})" >> $GITHUB_ENV

      - name: Run the tests
        run: npm run test
        env:
          ELECTROLUX_API_KEY: ${{ secrets.ELECTROLUX_API_KEY }}
          ELECTROLUX_ACCESS_TOKEN: ${{ env.ELECTROLUX_ACCESS_TOKEN }}